import os
import re
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'generated_files')


def ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return OUTPUT_DIR


def generate_pdf(title: str, content: str, filename: str = None) -> tuple:
    """
    Generate a PDF from title and content.
    Returns: (success: bool, filepath: str, message: str)
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        output_dir = ensure_output_dir()

        if not filename:
            safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')[:40]
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"{safe_title}_{timestamp}.pdf"

        filepath = os.path.join(output_dir, filename)

        # Build PDF
        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            fontSize=24,
            textColor=colors.HexColor('#0ea5e9'),
            spaceAfter=12,
            alignment=TA_CENTER,
        )
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=16,
            spaceAfter=8,
        )
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8,
            leading=16,
        )
        meta_style = ParagraphStyle(
            'Meta',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.HexColor('#94a3b8'),
            alignment=TA_CENTER,
        )

        story = []

        # Header
        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(
            f"Generated by ZeroTrace AI · {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            meta_style
        ))
        story.append(Spacer(1, 0.2 * inch))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0')))
        story.append(Spacer(1, 0.3 * inch))

        # Content — parse sections and paragraphs
        lines = content.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.1 * inch))
                continue

            # Detect headings (lines starting with # or ** or all caps short lines)
            if line.startswith('# '):
                story.append(Paragraph(line[2:], heading_style))
            elif line.startswith('## '):
                story.append(Paragraph(line[3:], heading_style))
            elif line.startswith('**') and line.endswith('**') and len(line) < 80:
                story.append(Paragraph(line.replace('**', ''), heading_style))
            elif line.startswith('• ') or line.startswith('- ') or line.startswith('* '):
                bullet_text = '• ' + line[2:]
                story.append(Paragraph(bullet_text, body_style))
            elif re.match(r'^\d+\.', line):
                story.append(Paragraph(line, body_style))
            else:
                # Clean markdown bold/italic for PDF
                clean = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
                clean = re.sub(r'\*(.*?)\*', r'<i>\1</i>', clean)
                story.append(Paragraph(clean, body_style))

        # Footer
        story.append(Spacer(1, 0.4 * inch))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#e2e8f0')))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(
            'Generated by ZeroTrace · Local AI · 100% Private · No cloud used',
            meta_style
        ))

        doc.build(story)
        return True, filepath, f'PDF created: {filename}'

    except ImportError:
        return False, '', 'ReportLab not installed. Run: pip install reportlab'
    except Exception as e:
        return False, '', f'PDF generation error: {str(e)}'


def parse_pdf_command(user_message: str) -> dict:
    """Extract PDF title and content from user message."""
    import re

    # Try to find a title
    title_match = re.search(r'(?:title|called|named)[:\s]+["\']?(.+?)["\']?(?:\n|$)', user_message, re.IGNORECASE)
    title = title_match.group(1).strip() if title_match else 'Document'

    # Content is the main body of the message
    content = user_message
    for phrase in ['create a pdf', 'make a pdf', 'generate pdf', 'write a pdf', 'create pdf']:
        content = re.sub(phrase, '', content, flags=re.IGNORECASE)

    return {'title': title, 'content': content.strip()}
